### ISSUE TITLE
grpc-demo-encryption服务端启动报错

### ISSUE THREAD

**Issue by mrdear** [yeyincai/grpc-demo#1]
服务端启动直接报这个错误,这是什么原因呢?
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.tomcat.jni.SSLContext.setCertificateBio(JJJLjava/lang/String;)Z
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.setKeyMaterial(ReferenceCountedOpenSslContext.java:664)
	at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.newSessionContext(ReferenceCountedOpenSslServerContext.java:114)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:349)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:334)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:414)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:402)
	at com.grpc.demo.encryption.SimpleServerStart.start(SimpleServerStart.java:27)
	at com.grpc.demo.encryption.SimpleServerStart.main(SimpleServerStart.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by yeyincai** [comment]
@nl101531 这两个jar升级一下版本  netty-tcnative、netty-tcnative-boringssl-static   version=1.1.33.Fork26

**Comment by mrdear** [comment]
@yeyincai thks,可以了.另外请教下有没有关于gRPC执行过程的分析讲解呢?看到拦截器那里有点晕晕的

**Comment by yeyincai** [comment]
@nl101531 https://skyao.gitbooks.io/leaning-grpc/content/ 可以参考下这为大神写的，源码看了几遍也没有完全融会贯通，不过自己写了一个rpc  [flashrpc](https://github.com/yeyincai/flashRPC)

**Comment by mrdear** [comment]
@yeyincai ok,谢谢指导
